version: '3.8'

services:
  api:
    build: .
    container_name: sequence-service
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgres_sequencing
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres_sequencing
      - DB_PORT=5000
      - DB_USER=docker
      - DB_PASS=docker
      - DB_NAME=sequencing
    command: supervisord -c /etc/supervisord.conf
    ports:
      - "3000:3000"

  postgres_sequencing:
    container_name: postgres_sequencing
    image: bitnami/postgresql:latest
    ports:
      - '5000:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sequencing
    volumes:
      - sequencing_pg_data:/bitnami/postgresql

volumes:
  sequencing_pg_data:
